# Generated by Django 2.2 on 2019-04-23 07:37

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=255)),
                ('clientAddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edgeID', models.AutoField(primary_key=True, serialize=False)),
                ('startNode', models.IntegerField(default=0)),
                ('endNode', models.IntegerField(default=0)),
                ('edgeLength', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeID', models.AutoField(primary_key=True, serialize=False)),
                ('nodeName', models.CharField(max_length=255)),
                ('nodeType', enumfields.fields.EnumField(enum=inventory.models.NodeType, max_length=1)),
                ('zone', enumfields.fields.EnumField(enum=inventory.models.ZoneType, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('palletID', models.AutoField(primary_key=True, serialize=False)),
                ('dimensions', models.CharField(max_length=255)),
                ('createDate', models.DateTimeField()),
                ('nodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('productPrice', models.IntegerField(default=0)),
                ('productDesc', models.CharField(max_length=255)),
                ('productDimensions', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('bundleID', models.AutoField(primary_key=True, serialize=False)),
                ('lotCode', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('dimentions', models.CharField(max_length=255)),
                ('createDate', models.DateTimeField()),
                ('palletID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Pallet')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('movementID', models.AutoField(primary_key=True, serialize=False)),
                ('movementDate', models.DateField()),
                ('movementType', enumfields.fields.EnumField(enum=inventory.models.MovementType, max_length=1)),
                ('bundleQuantity', models.IntegerField(default=0)),
                ('productBundleID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.ProductBundle')),
                ('productID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.Product')),
            ],
        ),
    ]
