# Generated by Django 2.2 on 2019-04-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientPhone',
            field=models.IntegerField(default=0),
        ),
    ]
