# Generated by Django 2.2 on 2019-04-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_client_clientphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientPhone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
